### ISSUE TITLE
Jan 10th - Morning Code Review Session

### ISSUE THREAD

**Issue by Rhelli** [Fig77/MNK-condition-test#6]
## Jan 10th Morning Code Review

- Line 35 `@logic_grid[@row]` - row is implicit - this may grow into misdirection which can be avoided if `@row` and `@column` are taken as arguments (👇)

- Minimise the use of instance variables and place emphasis on given arguments, so `@row` and `@column` should be given as arguments instead of instance variables

- This will make it easier for programmers to approach your code and read it (👆)

- Instead of calculating values, consider using constants to set a precalculated value to  make your code more readable and shorter

- Consider refactoring your code for for **get_row_column(index)** as per the following:

```
def get_row_column(index)
  @row = index / 3
  @column = index % 3
end
```

- Line 4 - Memory use - Consider creating independent variables to assess vectors by themselves. I.e. check the first row , check the second row, check the third row.. etc And then set a win on the first match.

-  👆 Using local variables (vs global) and limiting your scope can make this job easier

**Comment by Fig77** [comment]
* Point 1 - 3. I feel like you'd still be jumping around the code the same way, since I'm creating the variable at the process input, and using it during checks. **I did however, organize the class in "more or less" order of execution, so you can go streamline when reading it.** (honestly I always do that, like in my css's, but wasn't expecting to show this code at least yet) I will read if there is another benefit of not using class instance there, beside being more robust not to use them (even thought they don't have access from outside the class, or any other place inside it)

> * Instead of calculating values, consider using constants to set a precalculated value to make your code more readable and shorter

I thought about it and seems like a "same case - worst case" scenario. **Same case would be if every input during the game is taken**. 

Worst case is, if it's not. Since each input processing will only happen once, even if someone repeats the same input (a bool check will prevent the input to pass through the same formula), if you pre-process every input during execution, you'll execute the same function N times where N is the number of maximun amount of valid inputs. Where if you do it when input happens, will be N being N the number of moves during the game.

Now, if you write the hash manually, it's better. But that won't be possible on the N-scenario.

* > Line 4 - Memory use - Consider creating independent variables to assess vectors by themselves. I.e. check the first row , check the second row, check the third row.. etc And then set a win on the first match.

Given the generic approach to the algorithm, making variables instead of a vector or some structure like such, it's not possible. Also during check time, it's better to check after input if there is a win, in that input, instead of going through every case.

 ```
def get_row_column(index)
  @row = index / 3
  @column = index % 3
end
```

Actually doesn't work, and now I remeber why. I am adjusting the input to the logic grid, not the 3x3 grid. Logic grid = [row1, row2, row3, col1, col2, col3, dg1, dg2].

**Comment by Fig77** [comment]
```
 def get_row_column(index)
   @row = index / 3
   @column = index % 3
 end
```
changed to 
```
  def getColumnRow(input)
    @column = ( (input - 1) % 3) + 3
    @row = ( (input - 1) / 3)
  end
```
to fit logic grid.

* Functions are in "order" of execution to give somewhat a sense of linear reading.
* Instanced variables @row and @column weren't changed since still seems reasonable to me to have them as instanced variable, since they are being used through the whole class.
* Point four had been noticed, but given the scope of this program and points established in the previous message, had not incur in any changes.

No more changes were made (yet), but this is not by far close to the final objective. Closing issue:)
